SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS audith;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE audith (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    id_user INT NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data JSON NOT NULL,
    ip JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (id_user) REFERENCES users(id) ON DELETE CASCADE
);
